[package]
name = "rcore-lkm"
version = "0.1.0"
authors = ["gjz010 <gjz010944@gmail.com>"]
edition = "2018"
description = "Loadable Kernel Module for rCore"

[dependencies]
log = "0.4"
spin = "0.5"
xmas-elf = "0.6"
